#!/bin/bash

#PBS -l nodes=1:ppn=1:gpus=1:gc_v100s

#PBS -l pmem=250gb

#PBS -l walltime=10:00:00

#PBS -A dfc13_mri

#PBS -l qos=mgc_mri

#PBS -N dl_train

#PBS -t 0

# activate conda environment
conda activate conda-default

cd ${HOME}/group/project/scripting/execution_scripts/machine_learning
python 220621_train_1vsall_model_by_metadata_v2.py ${PBS_ARRAYID}

#python 220617_train_1vsall_model_by_metadata_ensemble_v2.py ${PBS_ARRAYID}



