#!/bin/bash

#PBS -l nodes=1:ppn=1

#PBS -l pmem=200gb

#PBS -l walltime=00:30:00

#PBS -A mzc267_a_g_sc_default

#PBS -N static_beam

#PBS -t 0-299

# activate conda environment
conda activate conda-default

# move to proper directory

#cd ${HOME}/group/project/scripting/output/beamforming

#mkdir 220304_time_dependent_beamforming_grids

#cd 211013_pca_energy_subset_job_array_proj

# script takes index as an argument
python ${HOME}/group/project/scripting/execution_scripts/beamforming/220308_static_beamforming_all_signals.py ${PBS_ARRAYID}

